### ISSUE TITLE
installing problem

### ISSUE THREAD

**Issue by shu-zha** [jabiercoding/dslforge#2]
hi when I use the link to install the dsl runtime 
http://dslforge.org/downloads/runtime/repository/
 it is shows me the error message:
Cannot complete the install because one or more required items could not be found.

  Software being installed: DSL Forge Runtime Feature 0.9.1.201703182347 (org.dslforge.runtime.feature.feature.group 0.9.1.201703182347)

  Missing requirement: Eclipse RAP Workspace Persistency 0.9.1.201703182347 (org.dslforge.workspace.jpa 0.9.1.201703182347) requires 'bundle org.eclipse.gemini.jpa 0.0.0' but it could not be found

  Cannot satisfy dependency:

    From: DSL Forge Runtime Feature 0.9.1.201703182347 (org.dslforge.runtime.feature.feature.group 0.9.1.201703182347)

To: org.dslforge.workspace.jpa [0.9.1.201703182347]

2.
I donnot know how to use git command:
Clone the repository: git clone https://github.com/plugbee/dslforge.git

**Comment by jabiercoding** [comment]
Hi Shuai,
I respond you by email. Please, when you have an issue report it to the official repository https://github.com/plugbee/dslforge , this issue is in a branch.
